export const root: string;
export const red: string;
export const green: string;
export const black: string;
export const circle: string;
export const screen: string;
export const presenter: string;
export const slides: string;
export const eyes: string;
